### ISSUE TITLE
Can't run chronicles

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad#115]
<img width="266" alt="image" src="https://github.com/equinor/mad/assets/22524448/35d2b1c5-0b89-45f1-9356-8d4f9911449b">

Steps to reproduce:

1. Run pnpm install - Ok
2. Run pnpm build:all - Ok
3. Run pnpm run:chronicles - Fails, 21 errors
4. When trying to run through Xcode, the errors from above show up. Apparently from the native code in React-native-skia

Xcode version: 14.3.1
Node version: 16.20.0
Npm version: 8.19.4
Pnpm version: 8.6.1

**Comment by HaakonSvane** [comment]
This issue has been bothering us (and the pipeline) since the latest xcode version and may be fixed by one or many of the following:

- Bump the Expo recommended version of react native skia to ..185
- Downgrade pnpm to the latest major 7 release. We have not tested 8, and have faced some issues with it. Should probably make an issue to upgrade.

Related: 
https://github.com/Shopify/react-native-skia/issues/1374

**Comment by tormodAase** [comment]
Tried with xcode 14.2, node 16.14.2, and pnpm 7.28.0, and it looks like it works. So I guess we have to somehow make this repo compatible with the newest versions, or specify in the readme which versions you should use.

**Comment by HaakonSvane** [comment]
The former would be appreciated 👍

**Comment by dansvend** [comment]
@tormodAase I think this was resolved by #131. Should the issue be closed?

**Comment by tormodAase** [comment]
duplicate of #130
