### ISSUE TITLE
What's new screen

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad#234]
### Package / App

Other

### Description

What's new screen exists in `mad-core`, but it's not been tested yet, and does not follow our new design.

### Requirements
- The screen should display the current version of the app's release notes.
- Contrary to `mad-expo-core`'s version of WhatsNew, it should *not* care about whether the release notes has been displayed to the user before. The screen should assume that if it is being displayed, it should do it's job.
- The screen should contain an "OK" button which will navigate the user to the next screen.
- [Should follow the design](https://www.figma.com/file/GmYi1qTwOkAM4ZyK5Bsj31/Component-library?type=design&node-id=3-19835&mode=dev)
- Should **not** contain a link to feedback screen for the time being.

**Comment by tormodAase** [comment]
@dansvend I believe it was you who requested a feedback button on the what's new screen. The way I understand it, we are going away from `feedback` and instead have a `create incident in service now` screen. Do we still want to link users to that screen?

**Comment by dansvend** [comment]
> @dansvend I believe it was you who requested a feedback button on the what's new screen. The way I understand it, we are going away from `feedback` and instead have a `create incident in service now` screen. Do we still want to link users to that screen?

Correct. It would be nice to encourage more feedback, but we probably don't want more ServiceNow tickets(?), so an alternative would be to give the users the option to give a thumbs up, middle thumb or thumbs down? 🤔 Another alternative is to let the users request functionality and turn them into GitHub issues automatically in respective repositories like we have in Flyt. What do you think is the best? More people should probably be involved in this discussion since this determines a common way we handle feedback and/or user requests.

**Comment by tormodAase** [comment]
@dansvend The way I see it, in the current state we only have a create incident screen, so until we have some other form of feedback planned, I suggest we don't include the feedback button at the what's new screen. It's not a requirement for the what's new screen itself, but possibly an improvement we can add in the future
